### ISSUE TITLE
error requesting data in `json` format

### ISSUE THREAD

**Issue by avelino** [gventuri/pandas-ai#32]
**traceback:**
```
Traceback (most recent call last):
  File "/Users/avelino/projects/buser/openapi/recommendation-next-travel/use-pandasai.py", line 43, in <module>
    print(pandas_ai.run(
          ^^^^^^^^^^^^^^
  File "/Users/avelino/projects/buser/openapi/recommendation-next-travel/.venv/lib/python3.11/site-packages/pandasai/__init__.py", line 120, in run
    answer = self.run_code(code, data_frame, False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avelino/projects/buser/openapi/recommendation-next-travel/.venv/lib/python3.11/site-packages/pandasai/__init__.py", line 166, in run_code
    exec(code)
  File "<string>", line 9, in <module>
NameError: name 'json' is not defined
```

**source:**

```py
data = {...}
df = pd.DataFrame(data)
llm = OpenAI()
pandas_ai = PandasAI(llm)

print(pandas_ai.run(
    df,
    prompt="""
    suggest when the next trip will be, destination and seat type,
    in JSON format: {"destination": "", "seat-type": ""}
    """))
```

## proposed solution

how **I solved it locally**, but I believe it is not the best way

add `import json` in `__init__.py`

**Comment by gventuri** [comment]
@avelino turns out the error was a different one. In some cases, OpenAI was returning an output like this:

```
result = {"happiness": 0.5, "gdp": 0.8}
print(result)
```

There was a conflict between the "print" listener and trying to print a variable that had been declared!
