### ISSUE TITLE
Error executing code when plotting with Matplotlib

### ISSUE THREAD

**Issue by AlexandreSajus** [gventuri/pandas-ai#400]
### 🐛 Describe the bug

I am trying to use PandasAI in conjunction with StarCoder to plot data using instructions, but it often fails when using matplotlib.

Here is an example, I wrote a simple script to load a dataset and prompt StarCoder using PandasAI to plot a pie chart:

```python
import pandas as pd
import matplotlib.pyplot as plt

from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder

SECRET_PATH = "secret.txt"
with open(SECRET_PATH, "r") as f:
    API_TOKEN = f.read()

llm = Starcoder(api_token=API_TOKEN)
pandas_ai = PandasAI(llm=llm, verbose=True)

DATA_PATH = "sales_data_sample.csv"

original_data = pd.read_csv(DATA_PATH, sep=",", encoding="ISO-8859-1")
original_data["ORDERDATE"] = pd.to_datetime(original_data["ORDERDATE"])
original_data = original_data.sort_values(by="ORDERDATE")

pandas_ai(original_data, "Plot a pie chart of sales by productline")
```

This generates correct code:
```python
df.groupby('PRODUCTLINE').sum()['SALES'].plot(kind='pie')
plt.show()
plt.close('all')
```

but fails with error:
```bash
<string>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
2023-07-27 16:41:01 [WARNING] Error executing code (count: 0)
<string>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
2023-07-27 16:41:04 [WARNING] Error executing code (count: 1)
<string>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
2023-07-27 16:41:05 [WARNING] Error executing code (count: 2)
2023-07-27 16:41:06 [INFO] Answer: 
2023-07-27 16:41:06 [INFO] Executed in: 6.89627480506897s
Exception ignored in: <function Shelf.__del__ at 0x000001BF2AD1B910>
Traceback (most recent call last):
  File "C:\Users\asaju\AppData\Local\Programs\Python\Python310\lib\shelve.py", line 162, in __del__
  File "C:\Users\asaju\AppData\Local\Programs\Python\Python310\lib\shelve.py", line 144, in close
  File "C:\Users\asaju\AppData\Local\Programs\Python\Python310\lib\shelve.py", line 172, in sync
  File "C:\Users\asaju\AppData\Local\Programs\Python\Python310\lib\dbm\dumb.py", line 120, in _commit
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _Database.close at 0x000001BF2C272F80>
Traceback (most recent call last):
  File "C:\Users\asaju\AppData\Local\Programs\Python\Python310\lib\dbm\dumb.py", line 274, in close
  File "C:\Users\asaju\AppData\Local\Programs\Python\Python310\lib\dbm\dumb.py", line 120, in _commit
TypeError: 'NoneType' object is not callable
```

Which is weird because if I run the generated code independently like so:
```python
import pandas as pd
import matplotlib.pyplot as plt

DATA_PATH = "sales_data_sample.csv"

original_data = pd.read_csv(DATA_PATH, sep=",", encoding="ISO-8859-1")
original_data["ORDERDATE"] = pd.to_datetime(original_data["ORDERDATE"])
original_data = original_data.sort_values(by="ORDERDATE")

original_data.groupby("PRODUCTLINE").sum()["SALES"].plot(kind="pie")
plt.show()
plt.close("all")
```

It does result in the correct pie chart:
![image](https://github.com/gventuri/pandas-ai/assets/62465003/a5565f34-94d6-49c8-ad1a-19796f5a3363)

Any ideas for a fix?

Here is the dataset used:
[sales_data_sample.csv](https://github.com/gventuri/pandas-ai/files/12184727/sales_data_sample.csv)

I am using:
- Python 3.10.6
- pandasai 0.6.12
- pandas 1.5.3
- matplotlib 3.7.2

**Comment by nautics889** [comment]
Hello, @AlexandreSajus.
I've been getting same error when investigating https://github.com/gventuri/pandas-ai/issues/353 (when running the code from the issue's description). So it's definetely unrelated to `Starcoder` language model and i doubt it's related to matplotlib as well.
___
Tried to run the script again, here what i've got:
_client2_BUG_341.py:_
```python
import pprint

import pandas as pd
from pandasai import PandasAI

# Sample DataFrame
df = pd.DataFrame({
    "house": ["a", "b", "c"],
    "happiness_index": [6.94, 7.16, 6.66],
	"people": [['abby', 'ben'], ['ken'], ['ian']]
})

# Instantiate a LLM
from pandasai.llm.openai import OpenAI
llm = OpenAI()

pandas_ai = PandasAI(llm)
pandas_ai.clear_cache()

response = pandas_ai.run(df, prompt='Which house has at least two people?')
print(response)
print("=" * 79)
pprint.pprint(pandas_ai.logs)

```
Output:
```
0    a
Name: house, dtype: object
===============================================================================
[{'level': 20, 'msg': 'Question: Which house has at least two people?'},
 {'level': 20, 'msg': 'Running PandasAI with openai LLM...'},
 {'level': 20, 'msg': 'Prompt ID: d468be57-caee-4d34-a246-4d5ec3b857b6'},
 {'level': 20,
  'msg': '\n'
         '                        Code generated:\n'
         '                        ```\n'
         '                        import pandas as pd\n'
         '\n'
         "data = {'house': ['c', 'b', 'a'],\n"
         "        'happiness_index': [7.16, 6.94, 6.66],\n"
         "        'people': [['ken'], ['abby', 'ben'], ['ian']]}\n"
         '\n'
         'df = pd.DataFrame(data)\n'
         '\n'
         "houses_with_two_people = df[df['people'].apply(lambda x: len(x) >= "
         "2)]['house']\n"
         '\n'
         'print(houses_with_two_people)\n'
         '                        ```\n'
         '                    '},
 {'level': 20,
  'msg': '\n'
         'Code running:\n'
         '```\n'
         "data = {'house': ['c', 'b', 'a'], 'happiness_index': [7.16, 6.94, "
         "6.66], 'people': [['ken'], ['abby', 'ben'], ['ian']]}\n"
         "houses_with_two_people = df[df['people'].apply(lambda x: len(x) >= "
         "2)]['house']\n"
         'print(houses_with_two_people)\n'
         '```'},
 {'level': 20, 'msg': 'Answer: 0    a\nName: house, dtype: object'},
 {'level': 20, 'msg': 'Executed in: 5.421868562698364s'}]
Exception ignored in: <function Shelf.__del__ at 0x0000023B2669A7A0>
Traceback (most recent call last):
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 162, in __del__
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 144, in close
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 172, in sync
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _Database.close at 0x0000023B27D17880>
Traceback (most recent call last):
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 275, in close
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable

Process finished with exit code 0

```
**Context:**

OS: Windows 11 Home (same as @AlexandreSajus as i see)
Interpreter: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] (differs from the one @AlexandreSajus uses)
pandasai version: HEAD from main branch ([`cc6f1d2`](https://github.com/gventuri/pandas-ai/commit/cc6f1d266a7032d972814483d39e5ac9d75d8a0d))
___
The problem arises from shelve module, when `PandasAI` is trying to save cache.

@AlexandreSajus, you can just disable caching and keep like that for a while:

```python
pandas_ai = PandasAI(llm=llm, verbose=True, enable_cache=False)
```
That worked for me, the problem disappeared.


___

@gventuri i guess the issues deserves to label bug :)

**Comment by gventuri** [comment]
@nautics889 thanks a lot for the investigation. Will investigate further to figure out whether it's a bug in the `shelve` library or something that is caused by us!

**Comment by AlexandreSajus** [comment]
Interesting and thanks for responding so quickly. Disabling caching does fix a part of the issue: I do not get the
```bash
TypeError: 'NoneType' object is not callable
```
error anymore.

But I still get the
```bash
2023-07-27 22:49:41 [WARNING] Error executing code (count: 0)
<string>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.   
2023-07-27 22:49:43 [WARNING] Error executing code (count: 1)
<string>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.   
2023-07-27 22:49:44 [WARNING] Error executing code (count: 2)
2023-07-27 22:49:45 [INFO] Answer: 
2023-07-27 22:49:45 [INFO] Executed in: 6.264588117599487s
```
error

**Comment by nautics889** [comment]
@AlexandreSajus 
ty for checking.
So, i guess we get we get two different errors: 
1. The first one is related to the code returned by (in your case) StartCoder. There was an issue being followed with a PR #371, i've added a logging when the snippet of returning code is trying to be executed.  [There ](https://github.com/gventuri/pandas-ai/pull/371/files#diff-62b472d83558337a7726ff6758a8c431481784a74add715c96e2fed8bedbbd63R678) is exactly the string which you've got in logs: `"Error executing code"` (and number of the attempt).
2. `TypeError` is related to the process of saving a cache - i guess it should be described in a separate issue (will create a new one later, probably not so important).

**Comment by AlexandreSajus** [comment]
Thanks for the answer! Do you know a way of debugging the `Error executing code` part? Since when I execute the generated code outside of PandasAI, it works fine

**Comment by nautics889** [comment]
>Do you know a way of debugging the Error executing code part? Since when I execute the generated code outside of PandasAI, it works fine

Kind of. I'll try to reproduce the code exactly from your query.

**Comment by AlexandreSajus** [comment]
Thanks a lot!

**Comment by nautics889** [comment]
@AlexandreSajus 
In brief, `PandasAI` can execute the code because there is no such thing as `plt` in the enviroment for running. There for it raises `NameError("name 'plt' is not defined")`.

___

`code_to_run` formed by HF:
```
"df.groupby('PRODUCTLINE').sum()['SALES'].plot(kind='pie')\nplt.show(block=False)\nplt.close('all')"
```
`environment` for execution these code:
```
{'pd': <module 'pandas' from '***\pandas-ai-venv\\Lib\\site-packages\\pandas\\__init__.py'>,
 '__builtins__': {'abs': <function abs(x, /)>,
  'all': <function all(iterable, /)>,
  'any': <function any(iterable, /)>,
  'ascii': <function ascii(obj, /)>,
  'bin': <function bin(number, /)>,
  'bool': bool,
  'bytearray': bytearray,
  'bytes': bytes,
  'callable': <function callable(obj, /)>,
  'chr': <function chr(i, /)>,
  'classmethod': classmethod,
  'complex': complex,
  'delattr': <function delattr(obj, name, /)>,
  'dict': dict,
  'dir': <function dir>,
  'divmod': <function divmod(x, y, /)>,
  'enumerate': enumerate,
  'filter': filter,
  'float': float,
  'format': <function format(value, format_spec='', /)>,
  'frozenset': frozenset,
  'getattr': <function getattr>,
  'hasattr': <function hasattr(obj, name, /)>,
  'hash': <function hash(obj, /)>,
  'help': Type help() for interactive help, or help(object) for help about object.,
  'hex': <function hex(number, /)>,
  'id': <function id(obj, /)>,
  'input': <function input(prompt='', /)>,
  'int': int,
  'isinstance': <function isinstance(obj, class_or_tuple, /)>,
  'issubclass': <function issubclass(cls, class_or_tuple, /)>,
  'iter': <function iter>,
  'len': <function len(obj, /)>,
  'list': list,
  'locals': <function locals()>,
  'map': map,
  'max': <function max>,
  'memoryview': memoryview,
  'min': <function min>,
  'next': <function next>,
  'object': object,
  'oct': <function oct(number, /)>,
  'open': <function io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
  'ord': <function ord(c, /)>,
  'pow': <function pow(base, exp, mod=None)>,
  'print': <function print(*args, sep=' ', end='\n', file=None, flush=False)>,
  'property': property,
  'range': range,
  'repr': <function repr(obj, /)>,
  'reversed': reversed,
  'round': <function round(number, ndigits=None)>,
  'set': set,
  'setattr': <function setattr(obj, name, value, /)>,
  'slice': slice,
  'sorted': <function sorted(iterable, /, *, key=None, reverse=False)>,
  'staticmethod': staticmethod,
  'str': str,
  'sum': <function sum(iterable, /, start=0)>,
  'super': super,
  'tuple': tuple,
  'type': type,
  'vars': <function vars>,
  'zip': zip},
 'df':  ***,
 '__warningregistry__': {'version': 139,
  ('The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.',
   FutureWarning,
   1): True}}
```
As you see above from the content of `environment`, neither `plt` nor even `myplotlib` as a package is present. As well as any other package that you could import to your main module.

____

I decided to make some expirement and modified `_get_environment()` method (exactly [here](https://github.com/gventuri/pandas-ai/blob/main/pandasai/__init__.py#L645)) — had added manually `matplotlib.pyplot` package to enviroment under `plt` alias, so it had been like:
```python
    def _get_environment(self) -> dict:
        """
        Returns the environment for the code to be executed.

        Returns (dict): A dictionary of environment variables
        """

        return {
            "pd": pd,
            "plt": matplotlib.pyplot,  # HERE IS WHAT I ADDED
```
And in the result, i've got the plot as you can see ![Screenshot 2023-07-29 023552](https://github.com/gventuri/pandas-ai/assets/31508183/36a8ae18-6e89-45d8-8d78-1808ef26fd2d)
___
@gventuri i guess we should handle somehow the issue with environment for running code. Futhermore, i'm actually still confusing with why HF returns code using exactly `plt` alias — i've inspected raw requests being sending to HF API ([this lines](https://github.com/gventuri/pandas-ai/blob/main/pandasai/llm/base.py#L340)), there is no any mention of `plt` in the `prompt`. 
Pls let me know if you have any ideas about this, i'd be eager to help.

**Comment by AlexandreSajus** [comment]
Thanks a lot for the detailed investigation! Can I fix this issue within my code, or should I do the same fix you did by editing the PandasAI package directly in my environment?

**Comment by nautics889** [comment]
@AlexandreSajus 
> Can I fix this issue within my code, or should I do the same fix you did by editing the PandasAI package directly in my environment?

As far as i get it, you can chose any of the options. Sure, the preferable way would be without modifying sources of pandas-ai and perhaps [a custom middleware](https://pandas-ai.readthedocs.io/en/latest/middlewares/) can help you with updating your client's code accordingly. Kind of that:
```python
from pandasai.middlewares.base import Middleware

class PrintMiddleware(Middleware):
    def run(self, code: str) -> str:
        return f"from matplotlib import pyplot as plt\n{code}"
```
_NOTE:_ i haven't tested this way yet, but guess it should works.

**Comment by AlexandreSajus** [comment]
INCREDIBLE!!! It works! Thanks a lot!

**Comment by gventuri** [comment]
@nautics889, thanks a lot for the fix. I guess we have 2 issues here:
- the one related to shelve which has it own dedicate issue (I'll try to work on it asap)
- i this very case, the problem is for some reason the LLM (starcoder) is not generating the code to import `from matplotlib import pyplot as plt`, which should be doing. I think in this case we should add some kind of default check so that if it uses one library, we automatically import it if it's not imported
