### ISSUE TITLE
Pandas v1.0.4 - Output of historical commands repeat + Plotting Issue

### ISSUE THREAD

**Issue by faisalalazem** [gventuri/pandas-ai#472]
### 🐛 Describe the bug

# I am trying to reproduce pandasai example using the latest 1.0.4 version
from pandasai import SmartDataframe
import pandas as pd
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})
sdf=SmartDataframe(df,config={"llm":llm})

#There is no problem with the first output
sdf.chat("Return the top 5 countries by GDP")

country	gdp	happiness_index
0	United States	19294482071552	6.94
9	China	14631844184064	5.12
8	Japan	4380756541440	5.87
3	Germany	3435817336832	7.07
1	United Kingdom	2891615567872	7.16

#However when I issue a new query, I get the output of the previous query

sdf.chat("What is the sum of the gdp of the 2 unhappiest countries?")

	country	gdp	happiness_index
0	United States	19294482071552	6.94
9	China	14631844184064	5.12
8	Japan	4380756541440	5.87
3	Germany	3435817336832	7.07
1	United Kingdom	2891615567872	7.16

#when I issue the query again, I finally get the correct output

sdf.chat("What is the sum of the gdp of the 2 unhappiest countries?")

19012600725504

# when I ask it to plot for me, I see the following error

sdf.chat(
    "Plot the histogram of countries showing for each the gdp, using different colors for each bar",
)

WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 292, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 199, in execute_code
    return analyze_data(self._get_original_dfs())
  File "<string>", line 12, in analyze_data
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'exports/charts/temp_chart.png'
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 2]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 292, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 176, in execute_code
    code_to_run = self._clean_code(code)
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 325, in _clean_code
    self._check_imports(node)
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 390, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of os which is not in whitelist.
WARNING:pandasai.helpers.logger:Error of executing code
Unfortunately, I was not able to answer your question, because of the following error:\n\n[Errno 2] No such file or directory: 'exports/charts/temp_chart.png'\n

# I see an output of the plots repeating 4 times

# When I ask a new query, I am again given the output of my last query for the sum of the 2 unhappiest countries

sdf.chat("What is the happiest country in Europe?")

19012600725504

# when I query again the same question, it executes the plotting command that gives me the plotting errors, and gives me again 4 plots.

sdf.chat("What is the happiest country in Europe?")

# when I ask it again the same query, I get the correct output

sdf.chat("What is the happiest country in Europe?")

The happiest country in Europe is United Kingdom.

#It seems that it is stuck in executing all the historical queries before executing the new query. Also seems there is an issue when we ask it to plot.

**Comment by faisalalazem** [comment]
fyi I tries the same commands for package pandasai==0.8.4 and I didnt experience any issues.

**Comment by PavelAgurov** [comment]
I have the same issue. I had to create folders before run:

`os.makedirs('exports/charts/')`

At least it helped me with problem 'Error of executing code'.

And looks like there is memory inside code that used to conversation, but not sure yet when.

**Comment by gventuri** [comment]
@faisalalazem @PavelAgurov thanks a lot for reporting. This has been fixed as of `v1.0.8`! Let me know if that works on your side too!
