### ISSUE TITLE
v1.1.2 missing file 

### ISSUE THREAD

**Issue by learningdeep2023** [gventuri/pandas-ai#536]
### 🐛 Describe the bug

Can be duplicated with pip install and 10 minutes to panadsai colab notebook.
v1.1.2 issue.

From colab notebook:

sdf = SmartDataframe(df, config={"llm": llm})

ERROR:pandasai.config:Could not load configuration
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/config.py", line 19, in load_config
    with open(find_closest("pandasai.json"), "r") as f:
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/path.py", line 37, in find_closest
    return os.path.join(find_project_root(filename), filename)
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/path.py", line 29, in find_project_root
    raise ValueError("Could not find the root folder of the project.")
ValueError: Could not find the root folder of the project.

**Comment by gventuri** [comment]
@learningdeep2023 thanks a lot for reporting, this bug has been fixed on 1.1.3!
