### ISSUE TITLE
FileNotFoundError: The file /content/temp_chart.png does not exist.

### ISSUE THREAD

**Issue by JunaidHassanCB** [gventuri/pandas-ai#748]
### System Info

os: google-colab
python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
pandas version: 1.5.3
pandasai version: 1.4.8

### 🐛 Describe the bug

I was using "Google Palm LLM" with "Pandas AI". When I tried to generate text, it works fine, but when I try to generate an image (figure or chart) I get the following error:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pandasai/responses/response_parser.py](https://localhost:8080/#) in format_plot(self, result)
     93         try:
---> 94             print(result)
     95             image = mpimg.imread(result["value"])

7 frames
FileNotFoundError: [Errno 2] No such file or directory: '/content/temp_chart.png'

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pandasai/responses/response_parser.py](https://localhost:8080/#) in format_plot(self, result)
     94             print(result)
     95             image = mpimg.imread(result["value"])
---> 96         except FileNotFoundError as e:
     97             raise FileNotFoundError(
     98                 f"The file {result['value']} does not exist."

FileNotFoundError: The file /content/temp_chart.png does not exist.
```

Summary of my code is as below:

```
from pandasai.helpers.openai_info import get_openai_callback

def chat_wrapper(sdf, chat_text):
  with get_openai_callback() as cb:
    response = sdf.chat(chat_text)

    return response, cb
    
from pandasai.llm import GooglePalm

google_palm_llm = GooglePalm(api_key=GOOGLE_PALM_API_KEY)

sdf1 = SmartDatalake([categories_df, orders_df, products_df, restaurants_df], config={"llm": google_palm_llm})

chat_wrapper(sdf1, 'What is the distribution of orders across different categories, and can you visualize the top-selling categories?')
```

**Comment by nautics889** [comment]
This happens because for some reason `temp_chart.png` hasn't been created [before the call of `.parse()` of the `ResponseParser`](https://github.com/gventuri/pandas-ai/blob/0712f8418a1fbc86c02cb4614e34573b965b366e/pandasai/smart_datalake/__init__.py#L517). @JunaidHassanCB could you please provide us a code generated by Google Palm? You can see one by specifying `verbose=True` for the config object, the code should appear somewhere among other logs.

**Comment by JunaidHassanCB** [comment]
I have done the following change to the code:

```
sdf1 = SmartDatalake([categories_df, orders_df, products_df, restaurants_df], config={"llm": google_palm_llm, "verbose":True})
```

But it is not giving more details, but if I expand the error message/frames I get more information like this:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pandasai/responses/response_parser.py](https://localhost:8080/#) in format_plot(self, result)
     93         try:
---> 94             image = mpimg.imread(result["value"])
     95         except FileNotFoundError as e:

7 frames
[/usr/local/lib/python3.10/dist-packages/matplotlib/image.py](https://localhost:8080/#) in imread(fname, format)
   1562             )
-> 1563     with img_open(fname) as image:
   1564         return (_pil_png_to_float_array(image)

[/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py](https://localhost:8080/#) in __init__(self, fp, filename)
    104             # filename
--> 105             self.fp = open(fp, "rb")
    106             self.filename = fp

FileNotFoundError: [Errno 2] No such file or directory: '/content/temp_chart.png'

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-38-5fdb268edbd1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 chat_wrapper(sdf1, 'What is the distribution of orders across different categories, and can you visualize the top-selling categories?')

[<ipython-input-20-d9aa05095174>](https://localhost:8080/#) in chat_wrapper(sdf, chat_text)
      3 def chat_wrapper(sdf, chat_text):
      4   with get_openai_callback() as cb:
----> 5     response = sdf.chat(chat_text)
      6 
      7     return response, cb

[/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py](https://localhost:8080/#) in chat(self, query, output_type)
    514             )
    515 
--> 516         result = self._query_exec_tracker.execute_func(
    517             self._response_parser.parse, result
    518         )

[/usr/local/lib/python3.10/dist-packages/pandasai/helpers/query_exec_tracker.py](https://localhost:8080/#) in execute_func(self, function, *args, **kwargs)
    124 
    125         try:
--> 126             result = function(*args, **kwargs)
    127 
    128             execution_time = time.time() - start_time

[/usr/local/lib/python3.10/dist-packages/pandasai/responses/response_parser.py](https://localhost:8080/#) in parse(self, result)
     53             return self.format_dataframe(result)
     54         elif result["type"] == "plot":
---> 55             return self.format_plot(result)
     56         else:
     57             return self.format_other(result)

[/usr/local/lib/python3.10/dist-packages/pandasai/responses/response_parser.py](https://localhost:8080/#) in format_plot(self, result)
     94             image = mpimg.imread(result["value"])
     95         except FileNotFoundError as e:
---> 96             raise FileNotFoundError(
     97                 f"The file {result['value']} does not exist."
     98             ) from e  # noqa: E501

FileNotFoundError: The file /content/temp_chart.png does not exist.
```

**Comment by JunaidHassanCB** [comment]
I think there was some problem with my Google Colab Notebook when I ran the same code on a different Notebook and in Pycharm it worked
Thanks, BTW

**Comment by aaossa** [comment]
I'm getting a similar error on `1.5.3` (both for Pandas and PandasAI). For some reason, it always fails the first time and regenerates the plot. In fact, if I set "save_charts" to True, two files are created: `temp_chart.png` and a `{some_hash}.png`. 

BTW, I would love to get the plot as a bytes object somehow or maybe in base64, so I can send it through an API, but I'm not sure how to proceed.

This is a code that reproduces the exception I'm seeing, I'm using the [Titanic dataset](https://github.com/datasciencedojo/datasets/blob/master/titanic.csv):

```python
from pathlib import Path
from os import environ

import pandas as pd
from pandasai import Agent
from pandasai.llm import OpenAI

df = pd.read_csv(Path("data", "titanic.csv"))
agent = Agent(
    [df],
    config={
        "llm": OpenAI(api_token=environ.get("OPENAI_API_KEY")),
        "verbose": True,
        "enforce_privacy": True,
        "enable_cache": True,
        "conversational": False,
        "save_charts": False,  # Or True. Both work as expected
        "open_charts": False,
    },
)

query = "What's the age distribution of the Titanic passengers?"
response = agent.chat(query)
print(response)  # Outputs None
```

This is the full output:

```
> poetry run python dev.py
2024-01-04 20:19:50 [INFO] Question: What's the age distribution of the Titanic passengers?
2024-01-04 20:19:50 [INFO] Running PandasAI with openai LLM...
2024-01-04 20:19:50 [INFO] Prompt ID: f778a32a-009f-4fe3-b3e6-616b56be203f
2024-01-04 20:19:50 [INFO] Executing Step 0: CacheLookup
2024-01-04 20:19:50 [INFO] Executing Step 1: PromptGeneration
2024-01-04 20:19:50 [INFO] Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }
```

Q: What's the age distribution of the Titanic passengers?
Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.



Generate python code and return full updated code:
2024-01-04 20:19:50 [INFO] Executing Step 2: CodeGenerator
2024-01-04 20:19:54 [INFO] HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-04 20:19:54 [INFO] Code generated:
            ```
            # TODO: import the required dependencies
import pandas as pd
import matplotlib.pyplot as plt

# Write code here
age_distribution = dfs[0]['Age'].plot(kind='hist', bins=20, edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Age Distribution of Titanic Passengers')
plt.show()

# Declare result var
result = {
    "type": "plot",
    "value": "age_distribution.png"
}
            ```

2024-01-04 20:19:54 [INFO] Executing Step 3: CachePopulation
2024-01-04 20:19:54 [INFO] Executing Step 4: CodeExecution
2024-01-04 20:19:54 [INFO] Saving charts to SOME_DIR/exports/charts/temp_chart.png
2024-01-04 20:19:54 [INFO] 
Code running:
```
age_distribution = dfs[0]['Age'].plot(kind='hist', bins=20, edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Age Distribution of Titanic Passengers')
plt.show()
result = {'type': 'plot', 'value': 'SOME_DIR/exports/charts/temp_chart.png'}
        ```
2024-01-04 20:19:56 [WARNING] Failed to execute code with a correction framework [retry number: 1]
2024-01-04 20:19:56 [ERROR] Failed with error: Traceback (most recent call last):
  File ".../python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 46, in execute  
    result = pipeline_context.query_exec_tracker.execute_func(
  File ".../python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 134, in execute_func
    step_data = self._generate_exec_step(tag, result)
  File ".../python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 183, in _generate_exec_step       
    self._response = self._format_response(result)
  File ".../python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 202, in _format_response
    with open(result["value"], "rb") as image_file:
FileNotFoundError: [Errno 2] No such file or directory: 'SOME_DIR/exports/charts/temp_chart.png'
. Retrying
2024-01-04 20:19:56 [INFO] Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
</dataframe>

The user asked the following question:
Q: What's the age distribution of the Titanic passengers?

You generated this python code:
# TODO: import the required dependencies
import pandas as pd
import matplotlib.pyplot as plt

# Write code here
age_distribution = dfs[0]['Age'].plot(kind='hist', bins=20, edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Age Distribution of Titanic Passengers')
plt.show()

# Declare result var
result = {
    "type": "plot",
    "value": "age_distribution.png"
}

It fails with the following error:
Traceback (most recent call last):
  File ".../python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 46, in execute  
    result = pipeline_context.query_exec_tracker.execute_func(
  File ".../python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 134, in execute_func
    step_data = self._generate_exec_step(tag, result)
  File ".../python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 183, in _generate_exec_step       
    self._response = self._format_response(result)
  File ".../python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 202, in _format_response
    with open(result["value"], "rb") as image_file:
FileNotFoundError: [Errno 2] No such file or directory: 'SOME_DIR/exports/charts/temp_chart.png'


Fix the python code above and return the new python code:
2024-01-04 20:19:59 [INFO] HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-04 20:19:59 [INFO] Saving charts to SOME_DIR/exports/charts/temp_chart.png
2024-01-04 20:19:59 [INFO] 
Code running:
```
age_distribution = dfs[0]['Age'].plot(kind='hist', bins=20, edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Age Distribution of Titanic Passengers')
plt.savefig('SOME_DIR/exports/charts/temp_chart.png')
plt.close()
result = {'type': 'plot', 'value': 'SOME_DIR/exports/charts/temp_chart.png'}
result
        ```
2024-01-04 20:20:00 [INFO] Executing Step 5: ResultValidation
2024-01-04 20:20:00 [INFO] Answer: {'type': 'plot', 'value': 'SOME_DIR/exports/charts/temp_chart.png'}
2024-01-04 20:20:00 [INFO] Executed in: 9.359991788864136s
2024-01-04 20:20:00 [INFO] Executing Step 6: ResultParsing
None
```

**Comment by Emad-Eldin-G** [comment]
Getting the same issue as well
