### ISSUE TITLE
[ERROR] Pipeline failed on step 4: All objects passed were None

### ISSUE THREAD

**Issue by ljdmitry** [gventuri/pandas-ai#823]
### System Info

Windows, pandasai 1.3.9, python 3.11.5

### 🐛 Describe the bug

Greetings, first of all, kudos to everyone involved in the development of this library! I have previously been using langchain with the fine-tuned gpt 3-5 turbo model to answer questions about my company's structured data, but switched to pandasai as soon as I heard about it since the potential of adding visualizations is tremendous :) Anywho, I am facing an issue right now and cannot generate a plot using the code below. Tried it with pandasai 1.3.6, 1.3.8 and 1.3.9 with largely the same effect

```
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI 

iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
llm2 = OpenAI(temperature=0, model="gpt-3.5-turbo-16k", api_token="sk-XXX")
pandas_ai2 = SmartDataframe(iris, config={"llm": llm2, "verbose": True})
response = pandas_ai2.chat("Please plot the histogram of average sepal_width for each specie, using different colors for each bar")
```

The log is as follows: 
```
"2023-12-15 13:36:00 [INFO] Question: Please plot the histogram of average sepal_width for each specie, using different colors for each bar
2023-12-15 13:36:00 [INFO] Running PandasAI with openai LLM...
2023-12-15 13:36:00 [INFO] Prompt ID: ed361326-14bb-4dd3-9856-60fa2bcc9981
2023-12-15 13:36:00 [INFO] Executing Step 0: CacheLookup
2023-12-15 13:36:00 [INFO] Using cached response
2023-12-15 13:36:00 [INFO] Executing Step 1: PromptGeneration
2023-12-15 13:36:00 [INFO] Executing Step 2: CodeGenerator
2023-12-15 13:36:00 [INFO] Executing Step 3: CachePopulation
2023-12-15 13:36:00 [INFO] Executing Step 4: CodeExecution
2023-12-15 13:36:00 [INFO] Saving charts to C:\Users\temp_chart.png
2023-12-15 13:36:00 [INFO] 
Code running:

df = pd.concat(dfs)
df.groupby('species')['sepal_width'].mean().plot(kind='bar', color=['skyblue', 'salmon', 'lightgreen'])
plt.title('Average Sepal Width for Each Species')
plt.xlabel('Species')
plt.ylabel('Average Sepal Width')
plt.show()
result = {'type': 'plot', 'value': 'C:\Users/temp_chart.png'}
        ```
2023-12-15 13:36:00 [WARNING] Failed to execute code with a correction framework [retry number: 1]
2023-12-15 13:36:00 [ERROR] Failed with error: Traceback (most recent call last):
  File "C:\Apps\anaconda\Lib\site-packages\pandasai\pipelines\smart_datalake_chat\code_execution.py", line 46, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\anaconda\Lib\site-packages\pandasai\helpers\query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\anaconda\Lib\site-packages\pandasai\helpers\code_manager.py", line 207, in execute_code
    exec(code_to_run, environment)
  File "<string>", line 1, in <module>
  File "C:\Apps\anaconda\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\anaconda\Lib\site-packages\pandas\core\reshape\concat.py", line 368, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "C:\Apps\anaconda\Lib\site-packages\pandas\core\reshape\concat.py", line 448, in __init__
    raise ValueError("All objects passed were None")
ValueError: All objects passed were None
. Retrying"

**Comment by gventuri** [comment]
Should have been fixed as of 1.5.10. Please, try to update and let me know! :)

**Comment by ljdmitry** [comment]
> Should have been fixed as of 1.5.10. Please, try to update and let me know! :)

Thanks for the quick reply! Just tried upgrading pandasai and it seems like version 1.5.9 is still the latest one - is 1.5.10 still enroute? 
![image](https://github.com/gventuri/pandas-ai/assets/100295381/8bee0272-3a3f-4c1e-939f-bc3274f6c6bf)

**Comment by gventuri** [comment]
Try now @ljdmitry :)

**Comment by gventuri** [comment]
@ljdmitry it's a pleasure!
